<a href="https://colab.research.google.com/github/Chosencodes/Anatomy-Prior-Guided-Multi-Organ-Segmentation/blob/main/Anatomy_Prior_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install remotezip -q

from remotezip import RemoteZip

url = "https://zenodo.org/records/10047292/files/Totalsegmentator_dataset_v201.zip?download=1"

with RemoteZip(url) as zf:
    names = zf.namelist()
    meta_candidates = [n for n in names if 'meta.csv' in n.lower()]
    print(meta_candidates)

['meta.csv']

In [3]:
with RemoteZip(url) as zf:
    zf.extract(meta_candidates[0], path='.')

import pandas as pd
df = pd.read_csv('meta.csv', sep=';')
%unload_ext google.colab.data_table
df

,image_id,age,gender,institute,study_type,split,manufacturer,scanner_model,kvp,pathology,pathology_location
0,s1366,50.0,NaN,I,ct polytrauma,train,siemens,sensation 64,120.0,unclear,unclear
1,s0245,77.0,m,I,ct abdomen-pelvis,train,siemens,somatom definition flash,100.0,no_pathology,no_location
2,s0325,65.0,f,I,ct abdomen-pelvis,train,siemens,sensation 64,120.0,other,abdomen
3,s0320,80.0,m,I,ct angiography abdomen-pelvis-leg,train,siemens,sensation 64,120.0,vascular,abdomen
4,s0193,63.0,m,C,ct abdomen-pelvis,train,siemens,emotion 16,130.0,no_pathology,no_location

In [6]:
%unload_ext google.colab.data_table
df

The google.colab.data_table extension is not loaded.

,image_id,age,gender,institute,study_type,split,manufacturer,scanner_model,kvp,pathology,pathology_location
0,s1366,50.0,NaN,I,ct polytrauma,train,siemens,sensation 64,120.0,unclear,unclear
1,s0245,77.0,m,I,ct abdomen-pelvis,train,siemens,somatom definition flash,100.0,no_pathology,no_location
2,s0325,65.0,f,I,ct abdomen-pelvis,train,siemens,sensation 64,120.0,other,abdomen
3,s0320,80.0,m,I,ct angiography abdomen-pelvis-leg,train,siemens,sensation 64,120.0,vascular,abdomen
4,s0193,63.0,m,C,ct abdomen-pelvis,train,siemens,emotion 16,130.0,no_pathology,no_location
...,...,...,...,...,...,...,...,...,...,...,...
1223,s1425,NaN,NaN,NaN,NaN,test,NaN,NaN,NaN,NaN,NaN
1224,s1426,68.0,m,NaN,NaN,test,ge,lightspeed pro 16,120.0,NaN,NaN
1225,s1427,23.0,m,NaN,NaN,test,ge,lightspeed16,120.0,NaN,NaN
1226,s1428,66.0,m,NaN,NaN,test,ge,discovery mi,120.0,NaN,NaN
1227,s1429,24.0,f,NaN,NaN,test,ge,optima ct680 series,120.0,NaN,NaN

In [7]:
from google.colab import files
files.download('meta.csv')

In [18]:
df['age'].value_counts().sort_values(ascending=False).reset_index().head(20)

     age  count
0   65.0     41
1   66.0     38
2   63.0     37
3   69.0     37
4   67.0     35
5   57.0     35
6   64.0     34
7   71.0     34
8   60.0     33
9   74.0     33
10  56.0     33
11  72.0     32
12  78.0     31
13  79.0     31
14  80.0     29
15  62.0     29
16  70.0     28
17  75.0     27
18  73.0     27
19  76.0     27

In [20]:
bins = [15, 30, 45, 60, 75, 99]
labels = ["15–29", "30–44", "45–59", "60–74", "75–98"]

df["age_group"] = pd.cut(
    df["age"],
    bins=bins,
    labels=labels,
    right=False
)

df["age_group"].value_counts().sort_index()

age_group
15–29     39
30–44     92
45–59    310
60–74    481
75–98    305
Name: count, dtype: int64

In [23]:
df["gender"].value_counts(dropna=False)

gender
m      716
f      510
NaN      2
Name: count, dtype: int64

In [24]:
df["pathology"].value_counts(dropna=False)

pathology
no_pathology    404
tumor           237
unclear         155
vascular        154
trauma           92
inflammation     86
other            61
NaN              24
bleeding         15
Name: count, dtype: int64

In [15]:
df['study_type'].value_counts().sort_values(ascending=False).reset_index().head(15)

                                study_type  count
0                 ct thorax-abdomen-pelvis    143
1            ct neck-thorax-abdomen-pelvis    114
2                        ct abdomen-pelvis     87
3                           ct thorax-neck     79
4                      ct angiography head     65
5                                  ct neck     65
6                                ct pelvis     55
7                        ct thorax-abdomen     54
8   ct angiography neck-thx-abd-pelvis-leg     50
9                               ct abdomen     48
10                           ct polytrauma     48
11                ct heart-thorakale aorta     46
12                                ct spine     41
13                       ct  intervention      40
14                         ct thorax-chest     39

In [25]:
df["institute"].value_counts(dropna=False)

institute
I      898
C       97
A       82
E       56
B       53
G       21
J        8
F        6
NaN      5
H        1
D        1
Name: count, dtype: int64

In [26]:
df["manufacturer"].value_counts(dropna=False)

manufacturer
siemens    1085
philips      74
ge           53
NaN          16
Name: count, dtype: int64

In [29]:
df["split"].value_counts(dropna=False)

split
train    1082
test       89
val        57
Name: count, dtype: int64

In [30]:
elderly_df = df[(df["age"] >= 70) & (df["age"] <= 98)].copy()

In [31]:
elderly_df

,image_id,age,gender,institute,study_type,split,manufacturer,scanner_model,kvp,pathology,pathology_location,age_group
1,s0245,77.0,m,I,ct abdomen-pelvis,train,siemens,somatom definition flash,100.0,no_pathology,no_location,75–98
3,s0320,80.0,m,I,ct angiography abdomen-pelvis-leg,train,siemens,sensation 64,120.0,vascular,abdomen,75–98
12,s0327,72.0,m,I,ct angiography neck-thx-abd-pelvis-leg,train,siemens,somatom definition as+,120.0,no_pathology,no_location,60–74
20,s0304,72.0,m,C,ct abdomen-pelvis,train,siemens,emotion 16,110.0,no_pathology,no_location,60–74
22,s0314,83.0,m,I,ct abdomen-pelvis,train,siemens,sensation 64,120.0,other,abdomen,75–98
...,...,...,...,...,...,...,...,...,...,...,...,...
1208,s0768,75.0,f,A,ct abdomen,train,siemens,somatom go.top,120.0,unclear,abdomen,75–98
1210,s0769,75.0,m,I,ct neck,train,siemens,somatom definition as+,100.0,inflammation,throat,75–98
1211,s0764,75.0,f,A,ct neck-thorax-abdomen-pelvis,train,siemens,somatom go.top,120.0,no_pathology,no_location,75–98
1214,s0759,80.0,f,A,ct neck-thorax-abdomen-pelvis,train,siemens,somatom go.top,120.0,tumor,thorax,75–98
1222,s1424,98.0,f,D,ct thorax-abdomen-pelvis,test,NaN,NaN,NaN,NaN,NaN,75–98

In [32]:
elderly_df["gender"].value_counts(dropna=False)

gender
m    266
f    193
Name: count, dtype: int64

In [33]:
elderly_df["age"].value_counts().sort_index()

age
70.0    28
71.0    34
72.0    32
73.0    27
74.0    33
75.0    27
76.0    27
77.0    26
78.0    31
79.0    31
80.0    29
81.0    22
82.0    21
83.0    17
84.0     9
85.0    14
86.0     8
87.0     8
88.0    12
89.0     2
90.0     7
91.0     1
92.0     1
93.0     5
94.0     5
96.0     1
98.0     1
Name: count, dtype: int64

In [34]:
pd.crosstab(
    df[df["age"].between(90, 98)]["age"],
    df[df["age"].between(90, 98)]["gender"]
)

gender  f  m
age
90.0    5  2
91.0    0  1
92.0    1  0
93.0    4  1
94.0    4  1
96.0    1  0
98.0    1  0

In [37]:
dataset = df[
    (df["age"].between(70, 89)) &
    (df["gender"].isin(["m", "f"])) &
    (df["pathology"] == "no_pathology")
].copy()

print("Number of subjects:", len(dataset))

dataset.head()

Number of subjects: 142

,image_id,age,gender,institute,study_type,split,manufacturer,scanner_model,kvp,pathology,pathology_location,age_group
1,s0245,77.0,m,I,ct abdomen-pelvis,train,siemens,somatom definition flash,100.0,no_pathology,no_location,75–98
12,s0327,72.0,m,I,ct angiography neck-thx-abd-pelvis-leg,train,siemens,somatom definition as+,120.0,no_pathology,no_location,60–74
20,s0304,72.0,m,C,ct abdomen-pelvis,train,siemens,emotion 16,110.0,no_pathology,no_location,60–74
24,s0312,78.0,f,I,ct spine,train,siemens,somatom definition as+,120.0,no_pathology,no_location,75–98
33,s0301,76.0,m,C,ct pelvis,train,siemens,emotion 16,130.0,no_pathology,no_location,75–98

In [39]:
pd.crosstab(dataset["age"], dataset["gender"])

gender  f   m
age
70.0    3   4
71.0    6   7
72.0    4   9
73.0    7   5
74.0    1   9
75.0    2   3
76.0    3   3
77.0    4   5
78.0    5   2
79.0    6  11
80.0    2   5
81.0    2   3
82.0    1   5
83.0    1   2
84.0    0   3
85.0    4   4
86.0    1   3
87.0    0   2
88.0    3   1
89.0    1   0

In [40]:
dataset["split"].value_counts()

split
train    134
test       5
val        3
Name: count, dtype: int64

In [41]:
dataset["study_type"].value_counts()

study_type
ct aortic valve                           19
ct thorax-neck                            18
ct thorax-abdomen-pelvis                  15
ct angiography head                       13
ct angiography neck-thx-abd-pelvis-leg    10
ct neck-thorax-abdomen-pelvis             10
ct spine                                   8
ct pelvis                                  8
ct abdomen-pelvis                          7
ct neck                                    5
ct polytrauma                              5
ct thorax-chest                            3
ct thorax                                  3
ct whole body                              3
ct heart-thorakale aorta                   3
ct heart                                   3
ct abdomen                                 2
ct  operation                              1
ct thorax-abdomen                          1
ct angiography thorax-abdomen-pelvis       1
ct chest                                   1
ct angiography thorax                      1
ct angiography neck                        1
ct left artrium                            1
Name: count, dtype: int64

In [42]:
# for a given organ, check whether the mask actually has content per study type
with RemoteZip(url) as zf:
    for pid, stype in df[['image_id','study_type']].values[:20]:
        seg_files = [n for n in zf.namelist() if n.startswith(f'{pid}/segmentations/liver')]
        print(pid, stype, seg_files)

s1366 ct polytrauma ['s1366/segmentations/liver.nii.gz']
s0245 ct abdomen-pelvis ['s0245/segmentations/liver.nii.gz']
s0325 ct abdomen-pelvis ['s0325/segmentations/liver.nii.gz']
s0320 ct angiography abdomen-pelvis-leg ['s0320/segmentations/liver.nii.gz']
s0193 ct abdomen-pelvis ['s0193/segmentations/liver.nii.gz']
s0189 ct aortic valve ['s0189/segmentations/liver.nii.gz']
s0330 ct  intervention  ['s0330/segmentations/liver.nii.gz']
s0329 ct abdomen-pelvis ['s0329/segmentations/liver.nii.gz']
s0326 ct neck ['s0326/segmentations/liver.nii.gz']
s0328 ct abdomen-pelvis ['s0328/segmentations/liver.nii.gz']
s0322 ct thorax-abdomen-pelvis ['s0322/segmentations/liver.nii.gz']
s0321 ct neck-thorax-abdomen-pelvis ['s0321/segmentations/liver.nii.gz']
s0327 ct angiography neck-thx-abd-pelvis-leg ['s0327/segmentations/liver.nii.gz']
s0324 ct abdomen-pelvis ['s0324/segmentations/liver.nii.gz']
s0049 ct aortic valve ['s0049/segmentations/liver.nii.gz']
s0315 ct thorax-chest ['s0315/segmentations/liver.nii.gz']
s0295 ct spine ['s0295/segmentations/liver.nii.gz']
s0311 ct abdomen-pelvis ['s0311/segmentations/liver.nii.gz']
s0319 ct abdomen-pelvis ['s0319/segmentations/liver.nii.gz']
s0316 ct  intervention  ['s0316/segmentations/liver.nii.gz']

In [43]:
import nibabel as nib
import numpy as np

def has_organ(zf, pid, organ='liver'):
    path = f'{pid}/segmentations/{organ}.nii.gz'
    zf.extract(path, path='./check')
    img = nib.load(f'./check/{path}')
    data = img.get_fdata()
    voxel_count = np.sum(data > 0)
    return voxel_count, voxel_count > 0

In [44]:
results = []
with RemoteZip(url) as zf:
    for pid, stype in df[['image_id','study_type']].values[:20]:
        voxels, present = has_organ(zf, pid, 'liver')
        results.append((pid, stype, voxels, present))

for r in results:
    print(r)

('s1366', 'ct polytrauma', np.int64(390876), np.True_)
('s0245', 'ct abdomen-pelvis', np.int64(341514), np.True_)
('s0325', 'ct abdomen-pelvis', np.int64(372401), np.True_)
('s0320', 'ct angiography abdomen-pelvis-leg', np.int64(352522), np.True_)
('s0193', 'ct abdomen-pelvis', np.int64(429128), np.True_)
('s0189', 'ct aortic valve', np.int64(495269), np.True_)
('s0330', 'ct  intervention ', np.int64(367827), np.True_)
('s0329', 'ct abdomen-pelvis', np.int64(696241), np.True_)
('s0326', 'ct neck', np.int64(0), np.False_)
('s0328', 'ct abdomen-pelvis', np.int64(600168), np.True_)
('s0322', 'ct thorax-abdomen-pelvis', np.int64(509643), np.True_)
('s0321', 'ct neck-thorax-abdomen-pelvis', np.int64(590677), np.True_)
('s0327', 'ct angiography neck-thx-abd-pelvis-leg', np.int64(382544), np.True_)
('s0324', 'ct abdomen-pelvis', np.int64(326874), np.True_)
('s0049', 'ct aortic valve', np.int64(529550), np.True_)
('s0315', 'ct thorax-chest', np.int64(971015), np.True_)
('s0295', 'ct spine', np.int64(0), np.False_)
('s0311', 'ct abdomen-pelvis', np.int64(553638), np.True_)
('s0319', 'ct abdomen-pelvis', np.int64(745078), np.True_)
('s0316', 'ct  intervention ', np.int64(0), np.False_)

In [45]:
selected_study_types = [
    "ct thorax-abdomen-pelvis",
    "ct abdomen-pelvis",
    "ct heart",
    "ct aortic valve"
]

df_selected = df[
    (df["age"].between(70, 89)) &
    (df["gender"].isin(["m", "f"])) &
    (df["pathology"] == "no_pathology") &
    (df["study_type"].isin(selected_study_types))
].copy()

print(df_selected.shape)

(44, 12)

In [46]:
print(df_selected["study_type"].value_counts())
print(df_selected["age"].value_counts().sort_index())
print(df_selected["gender"].value_counts())

study_type
ct aortic valve             19
ct thorax-abdomen-pelvis    15
ct abdomen-pelvis            7
ct heart                     3
Name: count, dtype: int64
age
70.0    1
71.0    3
72.0    6
73.0    3
74.0    3
76.0    2
77.0    4
78.0    1
79.0    6
80.0    2
81.0    1
82.0    2
83.0    1
85.0    3
86.0    2
87.0    1
88.0    2
89.0    1
Name: count, dtype: int64
gender
m    27
f    17
Name: count, dtype: int64

In [47]:
selected_study_types = [
    "ct thorax-abdomen-pelvis",
    "ct neck-thorax-abdomen-pelvis",
    "ct abdomen-pelvis",
    "ct thorax-abdomen",
    "ct angiography thorax-abdomen-pelvis",
    "ct angiography neck-thx-abd-pelvis-leg",
    "ct polytrauma"
]

selected_df = df[
    df["study_type"].isin(selected_study_types)
].copy()

In [48]:
selected_df["age"].describe()

count    513.000000
mean      62.485380
std       14.759408
min       17.000000
25%       53.000000
50%       64.000000
75%       73.000000
max       98.000000
Name: age, dtype: float64

In [56]:
# 50 years and below
below_50 = selected_df[selected_df["age"] <= 49]

# 51 years and above
above_51 = selected_df[selected_df["age"] >= 50]

print("Age 50 and below:", len(below_50))
print("Age 51 and above:", len(above_51))

Age 50 and below: 89
Age 51 and above: 424

In [58]:
no_pathology_under_50 = selected_df[
    (selected_df["age"] >= 50) &
    (selected_df["pathology"] == "no_pathology")
]

print("No-pathology cases age 50 and below:", len(no_pathology_under_50))

No-pathology cases age 50 and below: 124

In [59]:
final_df = df[
    (df["age"].between(50, 98)) &
    (df["study_type"].isin([
        "ct thorax-abdomen-pelvis",
        "ct neck-thorax-abdomen-pelvis",
        "ct abdomen-pelvis",
        "ct thorax-abdomen",
        "ct angiography thorax-abdomen-pelvis",
        "ct angiography neck-thx-abd-pelvis-leg",
        "ct polytrauma"
    ]))
].copy()

In [60]:
print("Total cases:", len(final_df))

Total cases: 424

In [62]:
normal_df = df[
    (df["age"].between(50, 98)) &
    (df["pathology"] == "no_pathology") &
    (df["study_type"].isin([
        "ct thorax-abdomen-pelvis",
        "ct neck-thorax-abdomen-pelvis",
        "ct abdomen-pelvis",
        "ct thorax-abdomen",
        "ct angiography thorax-abdomen-pelvis",
        "ct angiography neck-thx-abd-pelvis-leg",
        "ct polytrauma"
    ]))
].copy()

print("Total normal cases:", len(normal_df))

print("\nAge distribution:")
print(normal_df["age"].value_counts().sort_index())

print("\nGender:")
print(normal_df["gender"].value_counts(dropna=False))

print("\nAge group:")
print(
    pd.cut(
        normal_df["age"],
        bins=[49, 59, 69, 79, 89, 98],
        labels=["50–59", "60–69", "70–79", "80–89", "90–98"]
    ).value_counts().sort_index()
)

Total normal cases: 124

Age distribution:
age
50.0    3
51.0    5
53.0    4
54.0    3
55.0    4
56.0    5
57.0    5
58.0    2
59.0    5
60.0    2
61.0    3
62.0    4
63.0    6
64.0    3
65.0    3
66.0    3
67.0    9
68.0    2
69.0    3
70.0    1
71.0    5
72.0    9
73.0    3
74.0    4
75.0    4
76.0    2
77.0    3
78.0    2
79.0    4
80.0    2
81.0    1
82.0    1
84.0    1
85.0    1
86.0    2
87.0    1
88.0    3
94.0    1
Name: count, dtype: int64

Gender:
gender
m    72
f    52
Name: count, dtype: int64

Age group:
age
50–59    36
60–69    38
70–79    37
80–89    12
90–98     1
Name: count, dtype: int64

In [63]:
study_types = [
    "ct thorax-abdomen-pelvis",
    "ct neck-thorax-abdomen-pelvis",
    "ct abdomen-pelvis",
    "ct thorax-abdomen",
    "ct angiography thorax-abdomen-pelvis",
    "ct angiography abdomen-pelvis"
]

normal_df = df[
    (df["age"].between(50, 89)) &
    (df["pathology"] == "no_pathology") &
    (df["study_type"].isin(study_types))
].copy()

print("Total cases:", len(normal_df))
print("\nStudy type breakdown:")
print(normal_df["study_type"].value_counts())
print("\nAge group breakdown:")
print(
    pd.cut(
        normal_df["age"],
        bins=[49, 59, 69, 79, 89],
        labels=["50–59", "60–69", "70–79", "80–89"]
    ).value_counts().sort_index()
)
print("\nGender:")
print(normal_df["gender"].value_counts(dropna=False))

Total cases: 102

Study type breakdown:
study_type
ct thorax-abdomen-pelvis                40
ct neck-thorax-abdomen-pelvis           28
ct abdomen-pelvis                       25
ct angiography abdomen-pelvis            4
ct thorax-abdomen                        3
ct angiography thorax-abdomen-pelvis     2
Name: count, dtype: int64

Age group breakdown:
age
50–59    33
60–69    35
70–79    27
80–89     7
Name: count, dtype: int64

Gender:
gender
m    55
f    47
Name: count, dtype: int64

In [64]:
import nibabel as nib
import numpy as np
import pandas as pd
from remotezip import RemoteZip

url = "https://zenodo.org/records/10047292/files/Totalsegmentator_dataset_v201.zip?download=1"

organs = [
    "liver",
    "spleen",
    "kidney_left",
    "kidney_right",
    "pancreas",
    "stomach",
    "urinary_bladder"
]

results = []

with RemoteZip(url) as zf:
    for pid in normal_df["image_id"]:
        row = {"image_id": pid}
        for organ in organs:
            path = f"{pid}/segmentations/{organ}.nii.gz"
            try:
                zf.extract(path, path="./check")
                img = nib.load(f"./check/{path}")
                voxel_count = int(np.sum(img.get_fdata() > 0))
                row[organ] = voxel_count
            except Exception as e:
                row[organ] = -1  # file missing or unreadable
        results.append(row)

coverage_df = pd.DataFrame(results)
coverage_df.to_csv("organ_coverage_check.csv", index=False)
coverage_df.head()

,image_id,liver,spleen,kidney_left,kidney_right,pancreas,stomach,urinary_bladder
0,s0245,341514,95164,7608,11731,14783,88758,0
1,s0193,429128,30560,44827,39497,28991,126661,29930
2,s0311,553638,58956,51800,51512,32051,57897,96293
3,s0319,745078,90319,73741,72780,14000,73517,66397
4,s0304,330170,48909,55120,49626,32705,92203,81364

In [65]:
complete_cases = coverage_df[(coverage_df[organs] > 0).all(axis=1)]
print("Cases with all 7 organs present:", len(complete_cases))

Cases with all 7 organs present: 77

In [67]:
normal_df

,image_id,age,gender,institute,study_type,split,manufacturer,scanner_model,kvp,pathology,pathology_location,age_group
1,s0245,77.0,m,I,ct abdomen-pelvis,train,siemens,somatom definition flash,100.0,no_pathology,no_location,75–98
4,s0193,63.0,m,C,ct abdomen-pelvis,train,siemens,emotion 16,130.0,no_pathology,no_location,60–74
17,s0311,55.0,m,C,ct abdomen-pelvis,test,siemens,emotion 16,130.0,no_pathology,no_location,45–59
18,s0319,67.0,m,I,ct abdomen-pelvis,train,siemens,somatom definition as+,100.0,no_pathology,no_location,60–74
20,s0304,72.0,m,C,ct abdomen-pelvis,train,siemens,emotion 16,110.0,no_pathology,no_location,60–74
...,...,...,...,...,...,...,...,...,...,...,...,...
1178,s0798,56.0,f,A,ct neck-thorax-abdomen-pelvis,train,siemens,somatom go.top,120.0,no_pathology,no_location,45–59
1180,s0765,54.0,f,I,ct thorax-abdomen-pelvis,train,siemens,somatom definition flash,100.0,no_pathology,no_location,45–59
1182,s0795,56.0,f,A,ct thorax-abdomen-pelvis,train,siemens,somatom go.top,140.0,no_pathology,no_location,45–59
1184,s0806,72.0,m,I,ct neck-thorax-abdomen-pelvis,train,siemens,somatom force,110.0,no_pathology,no_location,60–74
1211,s0764,75.0,f,A,ct neck-thorax-abdomen-pelvis,train,siemens,somatom go.top,120.0,no_pathology,no_location,75–98

In [70]:
import os

print("Current /content usage:")
os.system("du -sh /content 2>/dev/null")

Current /content usage:

0

In [ ]:
import os
import shutil
from google.colab import drive

# Mount Google Drive (will prompt for auth the first time)
drive.mount('/content/drive')

download_ids = complete_cases["image_id"].tolist()
save_root = "./data"
drive_backup_root = "/content/drive/MyDrive/organ_segmentation_backup"
os.makedirs(drive_backup_root, exist_ok=True)

organs = [
    "liver",
    "spleen",
    "kidney_left",
    "kidney_right",
    "pancreas",
    "stomach",
    "urinary_bladder"
]

with RemoteZip(url) as zf:
    for pid in download_ids:
        patient_dir = f"{save_root}/{pid}"
        drive_patient_dir = f"{drive_backup_root}/{pid}"

        # skip if already backed up (lets you safely re-run after a crash)
        if os.path.exists(f"{drive_patient_dir}/segmentations/urinary_bladder.nii.gz"):
            print(f"Skipping {pid} (already backed up)")
            continue

        os.makedirs(f"{patient_dir}/segmentations", exist_ok=True)

        # download CT scan
        ct_path = f"{pid}/ct.nii.gz"
        zf.extract(ct_path, path=save_root)

        # download each organ mask
        for organ in organs:
            mask_path = f"{pid}/segmentations/{organ}.nii.gz"
            zf.extract(mask_path, path=save_root)

        # back up this patient's folder to Google Drive
        shutil.copytree(patient_dir, drive_patient_dir, dirs_exist_ok=True)

        print(f"Done + backed up: {pid}")

print("All downloads complete.")

Mounted at /content/drive
Done + backed up: s0193
Done + backed up: s0311
Done + backed up: s0319
Done + backed up: s0304
Done + backed up: s0298
Done + backed up: s0255
Done + backed up: s0250
Done + backed up: s0227
Done + backed up: s0218
Done + backed up: s0042
Done + backed up: s0174
Done + backed up: s0201
Done + backed up: s0190
Done + backed up: s0108
Done + backed up: s0089
Done + backed up: s0158
Done + backed up: s0151
Done + backed up: s0157
Done + backed up: s0137
Done + backed up: s0133
Done + backed up: s0120
Done + backed up: s0098
Done + backed up: s0086
Done + backed up: s0090
Done + backed up: s0028
Done + backed up: s0030
Done + backed up: s0010
Done + backed up: s0004
Done + backed up: s0001
Done + backed up: s0657
Done + backed up: s0731
Done + backed up: s0680
Done + backed up: s0686

In [ ]:
print("Total cases:", len(coverage_df))